#!/bin/sh
set -e

fatal() { echo "fatal: $*" 1>&2; exit 1; }

[ "$WIRELEAP_SOCKS" ] || fatal "WIRELEAP_SOCKS not set"

cmd="/Applications/Chromium Browser.app/Contents/MacOS/Chromium Browser"
[ -e "$cmd" ] || fatal "$cmd not found"

exec "$cmd" \
    --proxy-server="socks5://$WIRELEAP_SOCKS" \
    --user-data-dir="$HOME/.config/chromium-browser-wireleap" \
    --incognito \
    "$@"
