#!/bin/sh
set -e

fatal() { echo "fatal: $*" 1>&2; exit 1; }

cmd="$(basename "$0")"
command -v "$cmd" >/dev/null || fatal "$cmd not found"
[ "$WIRELEAP_SOCKS" ] || fatal "WIRELEAP_SOCKS not set"

exec "$cmd" -c http.proxy=socks5h://$WIRELEAP_SOCKS "$@"
