#!/bin/sh
set -e

fatal() { echo "fatal: $*" 1>&2; exit 1; }

[ "$WIRELEAP_SOCKS" ] || fatal "WIRELEAP_SOCKS not set"

cmd="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
[ -e "$cmd" ] || fatal "$cmd not found"

exec "$cmd" \
    --proxy-server="socks5://$WIRELEAP_SOCKS" \
    --user-data-dir="$HOME/.config/google-chrome-wireleap" \
    --incognito \
    "$@"
