#!/bin/sh
set -e

fatal() { echo "fatal: $*" 1>&2; exit 1; }

[ "$WIRELEAP_SOCKS" ] || fatal "WIRELEAP_SOCKS not set"

cmd="$(basename "$0")"
command -v "$cmd" >/dev/null || fatal "$cmd not found"

exec "$cmd" \
    --proxy-server="socks5://$WIRELEAP_SOCKS" \
    --user-data-dir="$HOME/.config/google-chrome-wireleap" \
    --incognito \
    "$@"
